# =========================
# MasterAI-Core Configuration
# =========================

server:
  host: 0.0.0.0
  # المنفذ سيأخذه تلقائياً من متغير البيئة PORT في Replit
  port: 5000

model:
  name: "masterai-small"        # اسم الموديل الافتراضي
  path: "./models/"             # مسار الموديلات
  use_gpu: false                # true إذا كنت تريد استخدام GPU، Replit عادة CPU فقط

memory:
  enable_memory: true           # تفعيل الذاكرة لتخزين المحادثات السابقة
  memory_path: "./memory/"      # مسار ملفات الذاكرة
  max_history: 10               # أقصى عدد من المحادثات التي تحفظ في الذاكرة

RAG:
  enable_rag: true              # تفعيل البحث عن المعرفة (Retrieval Augmented Generation)
  knowledge_path: "./knowledge/" # مجلد النصوص / المصادر
  top_k: 5                      # عدد أفضل المستندات المرجعية للرد

logging:
  level: "INFO"                 # DEBUG / INFO / WARNING / ERROR
  log_file: "./logs/masterai.log"

ui:
  enable_gradio: true           # تفعيل واجهة الدردشة Gradio
  gradio_title: "MasterAI-Core Chat"
  gradio_description: "تحدث مباشرة مع ذكاء MasterAI-Core"
